---
api:         2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core:        "7.x"

projects:

  # Core.
  drupal:
    version: "7.56"
    patch:
      - "https://www.drupal.org/files/issues/drupal-7.x-allow_profile_change_sys_req-1772316-28.patch"
      - "https://www.drupal.org/files/issues/drupal-1470656-26.patch"
      - "https://www.drupal.org/files/issues/core-111702-99-use_replyto.patch"

  # Distribution.
  govcms:
    version: "2.15"

  # Other modules.
  devel:
    version: "1.5"
    subdir:  "contrib"
